"""Add picture column to Site table

Revision ID: 677875e2f31f
Revises: 
Create Date: 2024-05-24 05:40:06.425657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677875e2f31f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
